[reddit.creds]
client_id = "KOhXUjTiMENoTKgPOZ4d1A"
client_secret = "72S9KhUH4Flsin04j1sP0OG8XO6CVw"
username = "Double-Squash-8247"
password = "xojnac-7fiXbo-mepfug"
2fa = false


[reddit.thread]
random = true
subreddit = "nosleep"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20

[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
#transition = { optional = true, default = 0.2, example = 0.2, explanation = "Sets the transition time (in seconds) between the comments. Set to 0 if you want to disable it.", type = "float", nmin = 0, nmax = 2, oob_error = "The transition HAS to be between 0 and 2", input_error = "The opacity HAS to be a decimal number between 0 and 2" }
storymode = true
storymodemethod= 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "pyttsx"
random_voice = true
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = "21f13f91f54d741e2ae27d2ab1b99d59"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "c76bcc3a7625abcc27b508c7db457ff1"
python_voice = "1"
py_voice_num = "2"
silence_duration = "0.1"
no_emojis = false
